CHECKLIST_SILVER_FIELDS = [
    "taxon_key",
    "dataset_key",
    "dataset_title",
    "scientific_name",
    "canonical_name",
    "taxon_rank",
    "taxonomic_status",
    "accepted_taxon_key",
    "accepted_scientific_name",
    "kingdom",
    "phylum",
    "class",
    "order",
    "family",
    "genus",
    "species",
    "authorship",
    "license",
    "references",
    "snapshot_date",
    "bronze_file_path",
]

